### PR TITLE
searchApi: fix "url" axios config override

### LINKED ISSUE #88: InvenioSearchApi: accidental use of both "baseURL" and "url" config
axios supports [both `url` and `baseURL` parameters](https://github.com/axios/axios#request-config), setting an absolute `url` though (i.e. `url: "https://localhost:5000/api/communities"`, cancels `baseURL`.

Setting [`baseURL: config.url`](https://github.com/inveniosoftware/react-searchkit/blob/001592c8edea81db429ae1be5bbb1d42c3998671/src/lib/api/contrib/invenio/InvenioSearchApi.js#L48) and then expanding the config via `...config`, is the equivalent of:

```javascript
const axiosConfig = {
  baseURL: config.url,
  url: config.url,
};
```

When a relative `url` is used (e.g. `url: "/api/communities"`), this causes the final requests to be made to `baseURL + url = "/api/communities/api/communities"`.

### PR DESCRIPTION
**Pull request by slint**
* Closes #88.

### CODE REVIEW

File: src/lib/api/contrib/elasticsearch/ESSearchApi.js [hunk 1]
```diff
@@ -41,12 +41,9 @@ export class ESSearchApi {
     this.responseSerializer = new responseSerializerCls();
   }
 
-  initAxios(config) {
+  initAxios({ url, ...config }) {
```
Comment (zzacharo) [inline src/lib/api/contrib/elasticsearch/ESSearchApi.js]: @slint How is this different than the existing implementation?
Before the code was expecting an object e.g `{url: '/me'}` and this would end up in the non desired behaviour of calling `/me/me` when it was triggering a request. Now with the change passing the passing the same object I think it would lead to the same outcome no? Unless you pass explicitly the `baseURL` parameter which in that case it was already possible before...Do I miss something?

Comment (slint) [reply src/lib/api/contrib/elasticsearch/ESSearchApi.js]: Since now `url` is a destructured value from the passed object function argument, it is will not be inside the `...config` object. This means that it won't be passed at all to the `axios.create(...)` call

Comment (zzacharo) [reply src/lib/api/contrib/elasticsearch/ESSearchApi.js]: But then you will not be able to pass the `url` parameter at all right?

Comment (slint) [reply src/lib/api/contrib/elasticsearch/ESSearchApi.js]: Yup. We have to discuss whether we'll directly pass-through the config to `axios.create(...)`, or if we'll introduce an `axiosConfig` parameter to the `ESSearchApi`/`InvneioSearchApi` class constructor.

Comment (zzacharo) [reply src/lib/api/contrib/elasticsearch/ESSearchApi.js]: @ntarocco what do you think? I would be in favor I think of name spacing the axios config like `axiosConfig` and pass it through to axios.

Comment (ntarocco) [reply src/lib/api/contrib/elasticsearch/ESSearchApi.js]: Are we discussing this? https://github.com/inveniosoftware/react-searchkit/issues/88
If yes, I should have already replied there :)

Comment (zzacharo) [reply src/lib/api/contrib/elasticsearch/ESSearchApi.js]: @ntarocco sorry I missed that. So just to confirm what you are proposing is just get through all the config passed to the axios instance right? In that case I wouldn't destructure the `url` parameter from the config passed and just pass through the config as it is. Then, it would be clear for the users (we should update the docs for that too) that this config is the same with what axios is accepting. @slint WDYT?

Comment (slint) [reply src/lib/api/contrib/elasticsearch/ESSearchApi.js]: I would go with an explicit `axiosConfig` parameter for the `InvenioSearchApi` constructor:

https://github.com/inveniosoftware/react-searchkit/blob/375f51db4b3859ddf809f97b513cc0f7e428c544/src/lib/api/contrib/invenio/InvenioSearchApi.js#L15-L16

So something like:

```javascript
export class InvenioSearchApi {
  constructor(serializers, axiosConfig, axiosInterceptors) {
    // NOTE: Would still validate the axiosConfig, but inside "initAxios"
    // this.validateConfig(config);
    this.initSerializers(serializers);
    this.initAxios(axiosConfig, axiosInterceptors);
  }
  ...
}
```

**Comment by slint** [comment]
LGTM :shipit: (I can't review my own PR apparently)
